### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by yoyololicon** [iamycy/diffwave-sr#9]
- [ ] update arxiv link
- [ ] update icassp proceedings
- [ ] setup autoforwarding for demo website
